apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cda-spark-kubernetes
  region: ap-south-1
  version: "1.20"

availabilityZones: ["ap-south-1a","ap-south-1b"]

nodeGroups:
  - name: spark-node-1
    instanceType: m5.large
    volumeSize: 30
    desiredCapacity: 2
    privateNetworking: true
    maxPodsPerNode: 10
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess 

cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["audit", "authenticator", "controllerManager"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"